name: rbbrainhack
channels:
  - conda-forge
dependencies:
  - python=2.7
  - jupyter
  - scikit-learn
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip:
    - git+git://github.com/mfalkiewicz/pySTATIS
    - git+git://github.com/satra/mapalign
    - nibabel
    - nilearn
    - matlab_kernel
